- name: "Change hostname {{ input_role_hostname_fqdn }}"
  hostname:
    name: "{{ input_role_hostname_fqdn.split('.')[0] }}"
#   notify:
#     - Reboot system

- name: "Change /etc/hosts in {{ input_role_hostname_fqdn }}"
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1       {{ input_role_hostname_fqdn.split('.')[0] }}       {{ input_role_hostname_fqdn }}"
    state: present
  when: input_role_hostname_fqdn.split('.') | length  > 1
#   notify:
#     - Reboot system

- name: "Change /etc/hosts in {{ input_role_hostname_fqdn }}"
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1       {{ input_role_hostname_fqdn.split('.')[0] }}"
    state: present
  when: input_role_hostname_fqdn.split('.') | length  <= 1
#   notify:
#     - Reboot system